insert into tags (tag) values ('русская классика');
insert into tags (tag) values ('дети');
insert into tags (tag) values ('магия');
insert into tags (tag) values ('рассказы');
insert into tags (tag) values ('школьная программа');
insert into tags (tag) values ('вампиры');
insert into tags (tag) values ('немецкая литература');
insert into tags (tag) values ('америка');
insert into tags (tag) values ('триллер');
insert into tags (tag) values ('советская литература');
insert into tags (tag) values ('книжное путешествие');
insert into tags (tag) values ('россия');
insert into tags (tag) values ('драма');
insert into tags (tag) values ('жизнь');
insert into tags (tag) values ('детство');
insert into tags (tag) values ('флэшмоб 2016');
insert into tags (tag) values ('флэшмоб 2015');
insert into tags (tag) values ('биография');
insert into tags (tag) values ('история');
insert into tags (tag) values ('война');
insert into tags (tag) values ('young adult');
insert into tags (tag) values ('дайте две');
insert into tags (tag) values ('франция');
insert into tags (tag) values ('роман');
insert into tags (tag) values ('антиутопия');
insert into tags (tag) values ('любимое');
insert into tags (tag) values ('экранизировано');
insert into tags (tag) values ('философия');
insert into tags (tag) values ('психология');
insert into tags (tag) values ('художественная литература');
insert into tags (tag) values ('англия');
insert into tags (tag) values ('французская литература');
insert into tags (tag) values ('сказка');
insert into tags (tag) values ('приключения');
insert into tags (tag) values ('юмор');
insert into tags (tag) values ('мистика');
insert into tags (tag) values ('любовь');
insert into tags (tag) values ('детектив');
insert into tags (tag) values ('детская литература');
insert into tags (tag) values ('фантастика');
insert into tags (tag) values ('американская литература');
insert into tags (tag) values ('русская литература');
insert into tags (tag) values ('английская литература');
insert into tags (tag) values ('фэнтези');
insert into tags (tag) values ('зарубежная литература');
insert into tags (tag) values ('классическая литература');
insert into tags (tag) values ('современная литература');


